# Languages
#   Create a section for each of your site's languages.
#   Documentation: https://docs.hugoblox.com/reference/language/

# Default language
en:
  languageCode: en-us
  # Uncomment for multi-lingual sites, and move English content into `en` sub-folder.
  contentDir: content/en

# Uncomment the lines below to configure your website in a second language.
ru:
  languageCode: "ru-ru"
  contentDir: "content/ru"
  menu:
    main:
      - name: Обо мне
        url: '#about'
        weight: 10
      - name: Посты
        url: '#posts'
        weight: 20
      - name: Проекты
        url: '#projects'
        weight: 30
      - name: Выступления
        url: '#talks'
        weight: 40
      - name: Публикации
        url: '#publication'
        weight: 50
      - name: Контакты
        url: '#contact'
        weight: 60
      - name: Биография
        url: '#biography'
        weight: 60
